// Generated by CoffeeScript 1.9.0
(function() {
  var ALPHABET, CSS_COLOR_NAMES, color_tab, debug, delay, id, interval, lambda_exemples, parentheses, speed, var_tab, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Array.prototype.unique = function() {
    var key, output, value, _i, _ref, _results;
    output = {};
    for (key = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ? ++_i : --_i) {
      output[this[key]] = this[key];
    }
    _results = [];
    for (key in output) {
      value = output[key];
      _results.push(value);
    }
    return _results;
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  interval = function(ms, func) {
    return setInterval(func, ms);
  };

  CSS_COLOR_NAMES = ["Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "Darkorange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkSlateGrey", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DimGrey", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Grey", "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGrey", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSlateGrey", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "SlateGrey", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen"];

  lambda_exemples = ["(λx.x) (λy.y)", "(λx.λy.x) (λy.y)", "((λy.y) (λz.z))(λx.x)", "(λx.λy. x) a b", "(λx.λy. y) a b", "(λa. a (λm.(λn. n ))(λp.(λq. p )))(λx.λy. y) a b", "(λx.x x) (λx.x x)", "λy.(λx.y (x x)) (λx.y (x x))", "(λa.λs.λz.s (a s z)) (λs.λz.z) ", "(λa.λb.λs.λz.(a s (b s z))) (λs.λz.(s z)) (λs.λz.(s z))", "(λa.λb.λs.λz.(a s (b s z))) (λs.λz.(s (s (s z)))) (λs.λz.(s (s (s (s z)))))"];

  ALPHABET = "abcdefghijklmnopqrstuvwxyz";

  _ref = [[], {}, false, true, 0, 0], color_tab = _ref[0], var_tab = _ref[1], debug = _ref[2], speed = _ref[3], id = _ref[4], parentheses = _ref[5];

  $(function() {
    var get_lambda_from, initialize_html, inserer, inserer_direct, make_dropped_droppable;
    (initialize_html = function() {
      var color, html, i, index, letter, _i, _j, _k, _len, _len1, _ref1, _ref2;
      _ref1 = ALPHABET.slice(0, 26);
      for (index = _i = 0, _len = _ref1.length; _i < _len; index = ++_i) {
        letter = _ref1[index];
        color_tab.push(CSS_COLOR_NAMES[index]);
        var_tab["" + letter] = CSS_COLOR_NAMES[index];
      }
      $.get("css/svg/egg.svg", function(rawSvg) {
        var importedSVGRootElement;
        importedSVGRootElement = document.importNode(rawSvg.documentElement, true);
        $("#egg-svg").append(importedSVGRootElement);
        return $("#egg-svg svg")[0].setAttribute('viewBox', '0 0 116 80');
      }, "xml");
      $.get("css/svg/open.svg", function(rawSvg) {
        var importedSVGRootElement;
        importedSVGRootElement = document.importNode(rawSvg.documentElement, true);
        $("#open-svg").append(importedSVGRootElement);
        return $("#open-svg svg")[0].setAttribute('viewBox', '-25 0 330 150');
      }, "xml");
      $.get("css/svg/vieux.svg", function(rawSvg) {
        var importedSVGRootElement;
        importedSVGRootElement = document.importNode(rawSvg.documentElement, true);
        $("#vieux-svg").append(importedSVGRootElement);
        return $("#vieux-svg svg")[0].setAttribute('viewBox', '0 0 228 78');
      }, "xml");
      html = "";
      for (i = _j = 0, _ref2 = lambda_exemples.length - 1; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; i = 0 <= _ref2 ? ++_j : --_j) {
        html += "<button id='ex-" + i + "' class='panel-button' data-type='exemple' data-numero='" + i + "'>" + i + "</button>";
      }
      $("#items").before(html);
      for (index = _k = 0, _len1 = color_tab.length; _k < _len1; index = ++_k) {
        color = color_tab[index];
        $("#choose-color").append("<div id='" + color + "' class='color' style='background-color:" + color + ";' data-color='" + color + "' data-variable='" + ALPHABET[index] + "'>" + ALPHABET[index] + "</div>");
      }
      $(".color").on("click", function() {
        var variable, _ref3;
        _ref3 = [$(this).attr("data-color"), $(this).attr("data-variable")], color = _ref3[0], variable = _ref3[1];
        $("#choose-color").attr("data-color", color);
        $("#panel-lambda").attr("data-variable", variable).html("λ" + variable);
        $("#panel-variable").attr("data-variable", variable).html("" + variable);
        $(".item").find(".skin").css("fill", color);
        $(".color").removeClass("selected-color");
        return $(this).addClass("selected-color");
      });
      $("#Blue").trigger("click");
      $(".item").draggable({
        helper: "clone",
        start: function(event, ui) {
          return $(ui.helper).addClass("ui-draggable-helper");
        },
        stop: function(event, ui) {
          return $(this).show();
        }
      });
      return $("#game-container").dialog({
        zIndex: 10,
        modal: true,
        show: {
          effect: 'fade',
          duration: 2000
        },
        hide: "size",
        width: "90%",
        height: Math.floor(90 * $(window).height() / 100),
        position: {
          my: "center",
          at: "center",
          of: window
        },
        open: function() {
          return $("body").addClass("stop-scrolling");
        },
        close: function() {
          return $("body").removeClass("stop-scrolling");
        }
      });
    })();
    $("#play").on("click", function() {
      return $("#game-container").dialog("open");
    });
    $(".panel-button").on("click", function() {
      var e, index, letter, _i, _len, _ref1, _results;
      switch ($(this).data("type")) {
        case "lambda":
          return $("#prompt").val($("#prompt").val() + ("(λ" + ($(this).data("variable")) + "."));
        case "variable":
          return $("#prompt").val($("#prompt").val() + (" " + ($(this).data("variable")) + " "));
        case "open":
          return $("#prompt").val($("#prompt").val() + "(");
        case "close":
          return $("#prompt").val($("#prompt").val() + ")");
        case "draw":
          e = jQuery.Event("keypress");
          e.which = 13;
          return $('#prompt').trigger(e);
        case "clear":
          parentheses = 0;
          $("#root").empty().append("<div id='root_definition' class='definition_drop'></div>");
          $("#prompt").val("");
          return make_dropped_droppable();
        case "exemple":
          $("#prompt").val(lambda_exemples[$(this).data("numero")]);
          e = jQuery.Event("keypress");
          e.which = 13;
          return $('#prompt').trigger(e);
        case "autoclose":
          parentheses = 0;
          _ref1 = $("#prompt").val();
          for (index = _i = 0, _len = _ref1.length; _i < _len; index = ++_i) {
            letter = _ref1[index];
            switch (letter) {
              case "(":
                parentheses += 1;
                break;
              case ")":
                parentheses -= 1;
            }
          }
          if (parentheses < 0) {
            return alert("il y a " + parentheses + " parenthese(s) fermée en trop !)");
          } else {
            _results = [];
            while (parentheses > 0) {
              $("#prompt").val($("#prompt").val() + ")");
              _results.push(parentheses -= 1);
            }
            return _results;
          }
          break;
        case "speed":
          $(this).html(speed ? "slow" : "fast");
          return speed = !speed;
        case "read":
          return $("#prompt").val(get_lambda_from($("#root")));
      }
    });
    get_lambda_from = function(root) {
      var exp, getKeyByValue;
      getKeyByValue = function(value) {
        var key;
        for (key in var_tab) {
          if (var_tab[key] === value) {
            return key;
          }
        }
      };
      exp = root.clone();
      exp.find("svg").remove();
      exp.find(".definition_drop").remove();
      exp.find(".application_drop").remove();
      exp = exp.html();
      exp = exp.replace(/<div id="\d+" class="variable dropped" data-variable="(\w+)"[ style="opacity: 1;"]*>\s*<\/div>/g, function(str, match) {
        return " " + getKeyByValue(match);
      });
      exp = exp.replace(/<div id="\d*" class="lambda dropped" data-variable="(\w+)"[ style="opacity: 1;"]*>/g, function(str, match) {
        return "(λ" + getKeyByValue(match) + ".";
      });
      exp = exp.replace(/<div id="\d*" class="lambda priorite dropped" data-variable="white"[ style="opacity: 1;"]*>/g, "(");
      return exp = exp.replace(/<\/div>/g, ")");
    };
    inserer_direct = function(symbole, droppable, mode) {
      var classe, color, lambda, type, _ref1, _ref2, _ref3;
      switch (symbole) {
        case "(":
          _ref1 = ["white", "lambda priorite", ".lambda.priorite"], color = _ref1[0], type = _ref1[1], classe = _ref1[2];
          lambda = $('<div/>').html("<div id='" + (id++) + "' class='" + type + " dropped' data-variable='" + color + "' ></div>").contents();
          $("#vieux-svg").clone().contents().prependTo($(lambda));
          break;
        default:
          if (ALPHABET.indexOf(symbole) > -1) {
            _ref2 = ["" + var_tab[symbole[0]], "variable", ".variable"], color = _ref2[0], type = _ref2[1], classe = _ref2[2];
            $("#egg-svg").find(".skin").css("fill", color);
            lambda = $('<div/>').html("<div id='" + (id++) + "' class='" + type + " dropped' data-variable='" + color + "' ></div>").contents();
            $("#egg-svg").clone().contents().prependTo($(lambda));
          } else {
            _ref3 = ["" + var_tab[symbole[1]], "lambda", ".lambda"], color = _ref3[0], type = _ref3[1], classe = _ref3[2];
            $("#open-svg").find(".skin").css("fill", color);
            lambda = $('<div/>').html("<div id='" + (id++) + "' class='" + type + " dropped' data-variable='" + color + "' ></div>").contents();
            $("#open-svg").clone().contents().prependTo($(lambda));
          }
      }
      return droppable = mode === "definition" ? droppable.append($(lambda)).children(classe).first() : droppable = droppable.after($(lambda)).next(classe);
    };
    $('#prompt').keypress(function(key) {
      var exp, i, local_debug, pointer, previous, symbole, _i, _ref1, _ref2, _ref3, _ref4, _ref5;
      local_debug = false;
      if (key.which === 13) {
        _ref1 = [$("#prompt").val(), $("#root").empty()], exp = _ref1[0], pointer = _ref1[1];
        _ref2 = [[], "", "none"], parentheses = _ref2[0], symbole = _ref2[1], previous = _ref2[2];
        for (i = _i = 0, _ref3 = exp.length - 1; 0 <= _ref3 ? _i <= _ref3 : _i >= _ref3; i = 0 <= _ref3 ? ++_i : --_i) {
          symbole += exp[i];
          if (local_debug) {
            alert(symbole);
          }
          switch (symbole) {
            case "(":
            case "λa.":
            case "λb.":
            case "λc.":
            case "λd.":
            case "λe.":
            case "λf.":
            case "λg.":
            case "λh.":
            case "λi.":
            case "λj.":
            case "λk.":
            case "λl.":
            case "λm.":
            case "λn.":
            case "λo.":
            case "λp.":
            case "λq.":
            case "λr.":
            case "λs.":
            case "λt.":
            case "λu.":
            case "λv.":
            case "λw.":
            case "λx.":
            case "λy.":
            case "λz.":
            case "a":
            case "b":
            case "c":
            case "d":
            case "e":
            case "f":
            case "g":
            case "h":
            case "i":
            case "j":
            case "k":
            case "l":
            case "m":
            case "n":
            case "o":
            case "p":
            case "q":
            case "r":
            case "s":
            case "t":
            case "u":
            case "v":
            case "w":
            case "x":
            case "y":
            case "z":
              if (local_debug) {
                alert("previous:" + previous);
              }
              switch (previous) {
                case "none":
                case "(":
                case "λa.":
                case "λb.":
                case "λc.":
                case "λd.":
                case "λe.":
                case "λf.":
                case "λg.":
                case "λh.":
                case "λi.":
                case "λj.":
                case "λk.":
                case "λl.":
                case "λm.":
                case "λn.":
                case "λo.":
                case "λp.":
                case "λq.":
                case "λr.":
                case "λs.":
                case "λt.":
                case "λu.":
                case "λv.":
                case "λw.":
                case "λx.":
                case "λy.":
                case "λz.":
                  pointer = inserer_direct(symbole, pointer, "definition");
                  if (previous === "(") {
                    parentheses.push(pointer.parent());
                  }
                  break;
                default:
                  pointer = inserer_direct(symbole, pointer, "application");
              }
              if (local_debug) {
                alert((symbole + " - new pointer is:") + pointer.attr("id"));
              }
              _ref4 = [symbole, ""], previous = _ref4[0], symbole = _ref4[1];
              break;
            case ")":
              pointer = parentheses.pop();
              _ref5 = [symbole, ""], previous = _ref5[0], symbole = _ref5[1];
              break;
            case " ":
              symbole = "";
              continue;
            default:
              continue;
          }
        }
        return false;
      }
    });
    inserer = function(draggable, droppable) {
      var lambda, type, variable;
      variable = draggable.hasClass("vieux-croco") ? 'white' : $("#choose-color").attr("data-color");
      if (draggable.hasClass("egg")) {
        type = "variable";
      } else if (draggable.hasClass("croco")) {
        type = "lambda";
      } else {
        type = "lambda priorite";
      }
      lambda = "<div id='" + (id++) + "' class='" + type + " dropped' data-variable='" + variable + "' ><div class='application_drop'></div></div>";
      lambda = $('<div/>').html(lambda).contents();
      if (type !== "variable") {
        $(lambda).prepend("<div class='definition_drop'></div>");
      }
      switch (type) {
        case "variable":
          $("#egg-svg").find(".skin").css("fill", variable);
          $("#egg-svg").clone().contents().prependTo($(lambda));
          break;
        case "lambda":
          $("#open-svg").find(".skin").css("fill", variable);
          $("#open-svg").clone().contents().prependTo($(lambda));
          break;
        case "lambda priorite":
          $("#vieux-svg").clone().contents().prependTo($(lambda));
      }
      if (droppable.hasClass("definition_drop")) {
        droppable.before($(lambda));
      } else {
        droppable.parent().after($(lambda));
      }
      return droppable.remove();
    };
    make_dropped_droppable = function() {
      return $(".application_drop, .definition_drop").droppable({
        hoverClass: "ui-state-hover",
        accept: ".item",
        drop: function(event, ui) {
          inserer(ui.draggable, $(this));
          return make_dropped_droppable();
        }
      });
    };
    make_dropped_droppable();
    $("#go").on("click", function() {
      var ahead_color, application, applicationClone, bust_a_move, color_rule_check, decapsule, delta, local_debug, pointer, stay, variable;
      local_debug = false;
      delta = speed ? 500 : 4000;
      $(".application_drop, .definition_drop").remove();
      pointer = $("#root > .lambda:first");
      ahead_color = ["white"];
      stay = true;
      decapsule = function(pointer) {
        var fragment;
        fragment = document.createDocumentFragment();
        while (pointer[0].firstChild) {
          fragment.appendChild(pointer[0].firstChild);
        }
        return pointer[0].parentNode.replaceChild(fragment, pointer[0]);
      };
      while (stay) {
        if (local_debug) {
          alert("stay for a loop");
        }
        ahead_color.push(pointer.data("variable"));
        if (pointer.hasClass("priorite")) {
          if (local_debug) {
            alert("Croco blanc !");
          }
          switch (pointer.children(":not(svg)").length) {
            case 1:
              pointer.find("svg").first().find("g#layer1").attr("transform", "rotate(180,140,65)");
              if (!speed) {
                alert("Ce vieil alligator ne sert plus à rien !");
              }
              pointer.find("svg").first().remove();
              decapsule(pointer);
              continue;
            default:
              if (pointer.find(".lambda").length > 0) {
                pointer = pointer.find(".lambda").first();
              } else {
                pointer = pointer.next();
              }
              continue;
          }
        }
        if ((pointer.hasClass("lambda")) && (!pointer.hasClass("priorite"))) {
          if (local_debug) {
            alert("Croco " + (pointer.data('variable')) + " !");
          }
          switch (pointer.next().length) {
            case 0:
              if (local_debug) {
                alert("has nothing to eat...go deeper");
              }
              if (pointer.find(".lambda").length > 0) {
                pointer = pointer.find(".lambda").first();
                continue;
              } else {
                if (local_debug) {
                  "nothing to eat, no deeper lambda...over !";
                }
                stay = false;
                continue;
              }
              break;
            default:
              stay = false;
              continue;
          }
        }
        if (pointer.hasClass("variable")) {
          if (local_debug) {
            alert("Oeuf " + (pointer.data('variable')) + " !");
          }
          pointer = pointer.next();
          continue;
        }
        if (local_debug) {
          alert("no if detected. breakin' !");
        }
        stay = false;
      }
      if ((pointer.hasClass("lambda")) && (pointer.data("color") !== "white") && (pointer.next().length > 0)) {
        ahead_color = ahead_color.unique();
        variable = pointer.data("variable");
        application = pointer.next();
        (color_rule_check = function(pointer, application) {
          var application_colors, application_items, color, difference, get_colors, index, item, new_color, pointer_colors, used_colors, _i, _j, _len, _len1, _results;
          get_colors = function(tree) {
            var palette;
            palette = [];
            tree.find("[data-variable]").andSelf().filter("[data-variable]").each(function() {
              return palette.push($(this).data("variable"));
            });
            return palette.unique();
          };
          pointer_colors = get_colors(pointer);
          _results = [];
          for (_i = 0, _len = pointer_colors.length; _i < _len; _i++) {
            color = pointer_colors[_i];
            application_items = application.find("[data-variable='" + color + "']").andSelf().filter("[data-variable='" + color + "']");
            if (application_items.length) {
              if (!speed) {
                alert("Règle de la couleur !(Color rule)");
              }
              application_colors = get_colors(application);
              used_colors = (pointer_colors.concat(application_colors.concat(ahead_color))).unique();
              difference = (function() {
                var _j, _len1, _results1;
                _results1 = [];
                for (_j = 0, _len1 = color_tab.length; _j < _len1; _j++) {
                  item = color_tab[_j];
                  if (__indexOf.call(used_colors, item) < 0) {
                    _results1.push(item);
                  }
                }
                return _results1;
              })();
              difference = difference.slice(0, +(application_colors.length - 1) + 1 || 9e9);
              for (index = _j = 0, _len1 = difference.length; _j < _len1; index = ++_j) {
                new_color = difference[index];
                application.find("[data-variable=" + application_colors[index] + "]").andSelf().filter("[data-variable=" + application_colors[index] + "]").each(function() {
                  var _ref1;
                  if (_ref1 = $(this).attr("data-variable"), __indexOf.call(ahead_color, _ref1) < 0) {
                    $(this).attr("data-variable", new_color);
                    return $(this).find(".skin").css("fill", new_color);
                  }
                });
              }
              if (!speed) {
                alert("C'est vu ?");
              }
              break;
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        })(pointer, application);
        applicationClone = application.clone();
        (bust_a_move = function(p, timer, j) {
          var bustit;
          bustit = interval(50, function() {
            return p.children("svg").css({
              "z-index": "9000"
            }).find("#jaw").attr("transform", "rotate(" + (-10 + Math.floor(6 * Math.cos(j++))) + ") translate(-100,20)");
          });
          return delay(timer, function() {
            clearInterval(bustit);
            pointer.children("svg").find("g#layer1").attr("transform", "rotate(180 125 75)");
            return pointer.children("svg").animate({
              "opacity": 0
            }, delta, function() {
              return $(this).closest("svg").remove();
            });
          });
        })(pointer, delta, 0);
        return application.css('visibility', 'hidden').clone().prependTo(pointer).css({
          "z-index": "-1",
          border: "dashed black 1px",
          visibility: "visible",
          position: "absolute",
          top: "0px",
          left: "100%"
        }).animate({
          "min-width": "0px",
          padding: "0px",
          height: '1vw',
          width: "1vw",
          top: "0",
          left: "60%"
        }, delta, function() {
          var eggs, n;
          $(this).remove();
          application.remove();
          eggs = pointer.find(".variable[data-variable=" + variable + "]");
          n = eggs.length;
          if (n > 0) {
            return eggs.each(function(index, element) {
              $(this).after(applicationClone.clone().css({
                opacity: 0
              }).animate({
                opacity: 1
              }, delta, function() {
                if (index === n - 1) {
                  return decapsule(pointer);
                }
              }));
              return $(this).animate({
                opacity: 0
              }, delta, function() {
                return $(this).remove();
              });
            });
          } else {
            if (!speed) {
              alert("Aucun oeuf !(no egg)");
            }
            return decapsule(pointer);
          }
        });
      }
    });
    return $(".run-previous-code").on("click", function() {
      var js;
      js = CoffeeScript.compile($(this).prev(":first").text());
      return eval(js);
    });
  });

}).call(this);
