// Generated by CoffeeScript 1.9.0
(function() {
  var color_tab, debug, id,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Array.prototype.unique = function() {
    var key, output, value, _i, _ref, _results;
    output = {};
    for (key = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ? ++_i : --_i) {
      output[this[key]] = this[key];
    }
    _results = [];
    for (key in output) {
      value = output[key];
      _results.push(value);
    }
    return _results;
  };

  debug = true;

  id = 1000;

  color_tab = ['purple', 'blue', 'LightBlue', 'red', 'orange', 'brown', 'green', 'LightGreen', 'yellow', 'pink', 'grey'];

  $(function() {
    var make_it_droppable, make_root_droppable;
    $(".color").on("click", function() {
      $("#choose-color").data("color", $(this).data("color"));
      $(".color").removeClass("selected-color");
      $(this).addClass("selected-color");
      if (debug) {
        return console.log("You choose " + $("#choose-color").data("color"));
      }
    });
    $(".item").draggable({
      helper: "clone",
      appendTo: "#buttons-panel"
    });
    make_it_droppable = function() {
      return $(".application_drop, .definition_drop").droppable({
        hoverClass: "ui-state-hover",
        accept: ".croco, .egg",
        drop: function(event, ui) {
          var lambda, variable;
          $(this).parent(":first").removeClass("parentHighlight");
          variable = $("#choose-color").data("color");
          if (ui.draggable.hasClass("croco")) {
            lambda = " <div id='" + (id++) + "' style='background-color:" + variable + ";' class='lambda dropped' data-variable='" + variable + "' >\n   <div class='definition_drop'></div>\n   <div class='application_drop'></div>\n</div>";
          } else {
            lambda = " <div id='" + (id++) + "' style='background-color:" + variable + ";' class='variable dropped' data-variable='" + variable + "' >\n   <div class='application_drop'></div>\n</div>";
          }
          if ($(this).hasClass("definition_drop")) {
            $(this).before(lambda);
          } else {
            $(this).parent().after(lambda);
          }
          $(this).remove();
          if (debug) {
            console.log("a " + $(lambda).data("variable") + " has been dropped !");
          }
          return make_it_droppable();
        }
      });
    };
    make_root_droppable = function() {
      return $("#root").droppable({
        hoverClass: "ui-state-hover",
        accept: ".croco",
        drop: function(event, ui) {
          var lambda, variable;
          variable = $("#choose-color").data("color");
          lambda = " <div id='" + (id++) + "' style='background-color:" + variable + ";' class='lambda dropped' data-variable='" + variable + "' >\n   <div class='definition_drop'></div>\n   <div class='application_drop'></div>\n</div>";
          $(this).append(lambda).droppable("destroy");
          if (debug) {
            console.log("a " + $(lambda).data("variable") + " has been dropped !");
          }
          return make_it_droppable();
        }
      });
    };
    make_root_droppable();
    $("#go").on("click", function() {
      var application_content, color_rule_check, definition_content, pointer, variable;
      $(".application_drop, .definition_drop").remove();
      pointer = $("#root > .lambda:first");
      while (!pointer.siblings().length) {
        pointer = pointer.find(".lambda").first();
        if (!pointer.length) {
          alert("over");
          break;
        }
      }
      variable = pointer.data("variable");
      color_rule_check = function(func, app) {
        var app_colors, app_items, color, difference, found, func_colors, index, item, new_color, used_colors, _i, _j, _len, _len1, _results;
        func_colors = [];
        func.find("[data-variable]").andSelf().filter("[data-variable]").each(function() {
          return func_colors.push($(this).data("variable"));
        });
        func_colors = func_colors.unique();
        found = false;
        _results = [];
        for (_i = 0, _len = func_colors.length; _i < _len; _i++) {
          color = func_colors[_i];
          app_items = app.find("[data-variable='" + color + "']").andSelf().filter("[data-variable='" + color + "']");
          if (app_items.length) {
            alert("Color Rule Alert !");
            app_colors = [];
            app.find("[data-variable]").andSelf().filter("[data-variable]").each(function() {
              return app_colors.push($(this).data("variable"));
            });
            app_colors = app_colors.unique();
            used_colors = (func_colors.concat(app_colors)).unique();
            difference = (function() {
              var _j, _len1, _results1;
              _results1 = [];
              for (_j = 0, _len1 = color_tab.length; _j < _len1; _j++) {
                item = color_tab[_j];
                if (__indexOf.call(used_colors, item) < 0) {
                  _results1.push(item);
                }
              }
              return _results1;
            })();
            difference = difference.slice(0, +(app_colors.length - 1) + 1 || 9e9);
            for (index = _j = 0, _len1 = difference.length; _j < _len1; index = ++_j) {
              new_color = difference[index];
              app.find("[data-variable=" + app_colors[index] + "]").andSelf().filter("[data-variable=" + app_colors[index] + "]").each(function() {
                $(this).attr("data-variable", new_color);
                return $(this).css("backgroundColor", new_color);
              });
            }
            alert("see?");
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      application_content = pointer.siblings().first();
      color_rule_check(pointer, application_content);
      pointer.find(".variable").each(function() {
        var element;
        element = $(this);
        if (debug) {
          console.log("j'ai trouvé un " + element.data("variable"));
        }
        if (element.data("variable") === variable) {
          element.before(application_content.clone());
          return element.remove();
        }
      });
      application_content.remove();
      definition_content = pointer.contents();
      pointer.after(definition_content);
      return pointer.remove();
    });
    $("#clear").on("click", function() {
      $("#root").empty();
      return make_root_droppable();
    });
    $("#ex-4").on("click", function() {
      var html;
      html = "<div id=\"1001\" style=\"background-color:yellow;\" class=\"lambda dropped\" data-variable=\"yellow\">\n  <div id=\"1002\" style=\"background-color:yellow;\" class=\"variable dropped\" data-variable=\"yellow\">\n \n</div> <div id=\"1003\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1004\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1010\" style=\"background-color:red;\" class=\"variable dropped\" data-variable=\"red\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n \n</div> <div id=\"1005\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1006\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1011\" style=\"background-color:LightGreen;\" class=\"variable dropped\" data-variable=\"LightGreen\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n \n</div> <div id=\"1007\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1008\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1009\" style=\"background-color:red;\" class=\"variable dropped\" data-variable=\"red\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>";
      $("#root").empty();
      return $("#root").append(html);
    });
    $("#ex-3").on("click", function() {
      var html;
      html = "<div id=\"1001\" style=\"background-color:yellow;\" class=\"lambda dropped\" data-variable=\"yellow\">\n  <div id=\"1002\" style=\"background-color:yellow;\" class=\"variable dropped\" data-variable=\"yellow\">\n \n</div> <div id=\"1003\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1004\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1010\" style=\"background-color:red;\" class=\"variable dropped\" data-variable=\"red\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n \n</div> <div id=\"1005\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1006\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1011\" style=\"background-color:LightGreen;\" class=\"variable dropped\" data-variable=\"LightGreen\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n \n</div> <div id=\"1007\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n  <div id=\"1008\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n  <div id=\"1009\" style=\"background-color:LightGreen;\" class=\"variable dropped\" data-variable=\"LightGreen\">\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>\n <div class=\"application_drop ui-droppable\"></div>\n</div>";
      $("#root").empty();
      return $("#root").append(html);
    });
    $("#ex-2").on("click", function() {
      var html;
      html = " <div id=\"1005\" style=\"background-color:purple;\" class=\"lambda dropped\" data-variable=\"purple\">\n <div id=\"1006\" style=\"background-color:orange;\" class=\"lambda dropped\" data-variable=\"orange\">\n <div id=\"1013\" style=\"background-color:purple;\" class=\"variable dropped\" data-variable=\"purple\">\n\n</div> <div id=\"1014\" style=\"background-color:purple;\" class=\"variable dropped\" data-variable=\"purple\">\n\n</div> <div id=\"1015\" style=\"background-color:orange;\" class=\"variable dropped\" data-variable=\"orange\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n\n</div> <div id=\"1007\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n <div id=\"1008\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n <div id=\"1011\" style=\"background-color:LightGreen;\" class=\"variable dropped\" data-variable=\"LightGreen\">\n\n</div> <div id=\"1012\" style=\"background-color:red;\" class=\"variable dropped\" data-variable=\"red\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n\n</div> <div id=\"1009\" style=\"background-color:yellow;\" class=\"lambda dropped\" data-variable=\"yellow\">\n <div id=\"1010\" style=\"background-color:yellow;\" class=\"variable dropped\" data-variable=\"yellow\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>";
      $("#root").empty();
      return $("#root").append(html);
    });
    $("#ex-1").on("click", function() {
      var html;
      html = " <div id=\"1001\" style=\"background-color:LightGreen;\" class=\"lambda dropped\" data-variable=\"LightGreen\">\n <div id=\"1002\" style=\"background-color:red;\" class=\"lambda dropped\" data-variable=\"red\">\n <div id=\"1007\" style=\"background-color:LightGreen;\" class=\"variable dropped\" data-variable=\"LightGreen\">\n\n</div> <div id=\"1008\" style=\"background-color:red;\" class=\"variable dropped\" data-variable=\"red\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n\n</div> <div id=\"1003\" style=\"background-color:LightBlue;\" class=\"lambda dropped\" data-variable=\"LightBlue\">\n <div id=\"1004\" style=\"background-color:blue;\" class=\"lambda dropped\" data-variable=\"blue\">\n <div id=\"1009\" style=\"background-color:LightBlue;\" class=\"variable dropped\" data-variable=\"LightBlue\">\n\n</div> <div id=\"1010\" style=\"background-color:blue;\" class=\"variable dropped\" data-variable=\"blue\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n\n</div> <div id=\"1005\" style=\"background-color:yellow;\" class=\"lambda dropped\" data-variable=\"yellow\">\n <div id=\"1006\" style=\"background-color:yellow;\" class=\"variable dropped\" data-variable=\"yellow\">\n<div class=\"application_drop ui-droppable\"></div>\n</div>\n<div class=\"application_drop ui-droppable\"></div>\n</div>";
      $("#root").empty();
      return $("#root").append(html);
    });
    return $(".run-previous-code").on("click", function() {
      var js;
      js = CoffeeScript.compile($(this).prev(":first").text());
      return eval(js);
    });
  });

}).call(this);
